// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvURh_Ar9VTVFKndo8jmSb6kvfpcdqrU',
    appId: '1:1085560411698:web:c68e93989663d01cca0e2b',
    messagingSenderId: '1085560411698',
    projectId: 'personal-profile-project-be477',
    authDomain: 'personal-profile-project-be477.firebaseapp.com',
    databaseURL: 'https://personal-profile-project-be477-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-profile-project-be477.appspot.com',
    measurementId: 'G-YBXX3M3NVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoZbwwQY9fwxRqIiAkVZF41AbsBzSTOI',
    appId: '1:1085560411698:android:3a20c1b00c230d7cca0e2b',
    messagingSenderId: '1085560411698',
    projectId: 'personal-profile-project-be477',
    databaseURL: 'https://personal-profile-project-be477-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-profile-project-be477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0oE5YB2uo6hzsW6I4ZXbzdx_sLRpRNk4',
    appId: '1:1085560411698:ios:7163d2d162448883ca0e2b',
    messagingSenderId: '1085560411698',
    projectId: 'personal-profile-project-be477',
    databaseURL: 'https://personal-profile-project-be477-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-profile-project-be477.appspot.com',
    iosBundleId: 'com.example.profile',
  );
}
